# Generated by Django 3.0.5 on 2020-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steganographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/original/', verbose_name='Оригинальное изображение')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='images/watermark/', verbose_name='Водяной знак')),
                ('fractal_key_image', models.ImageField(blank=True, null=True, upload_to='images/fractal/', verbose_name='Фрактальный ключ')),
                ('stego_image', models.ImageField(blank=True, null=True, upload_to='images/stego/', verbose_name='Стегоизображение')),
                ('is_ok', models.BooleanField(default=False, verbose_name='Стегоконтейнер готов')),
                ('has_errors', models.BooleanField(default=False, verbose_name='Есть ошибки')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
