# Generated by Django 3.0.5 on 2020-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steganographic',
            name='text',
            field=models.CharField(blank=True, default='Здесь могла бы быть умная цитата', max_length=500, null=True, verbose_name='Данные для qr-кода'),
        ),
    ]
