# Generated by Django 3.0.5 on 2020-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_steganographic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='steganographic',
            name='fractal_key_with_watermark',
            field=models.ImageField(blank=True, null=True, upload_to='images/fractal_with_watermark/', verbose_name='Ключ со встроенным ЦВЗ'),
        ),
    ]
