# Generated by Django 3.0.5 on 2020-05-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mainlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='steganographic',
            name='is_decrypt',
            field=models.BooleanField(default=True, verbose_name='Сокрытие'),
        ),
        migrations.AddField(
            model_name='steganographic',
            name='tech_info',
            field=models.TextField(blank=True, null=True, verbose_name='Тех. информация о контейнере'),
        ),
        migrations.AlterField(
            model_name='steganographic',
            name='is_ok',
            field=models.BooleanField(default=False, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='steganographic',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/original/', verbose_name='Оригинальное изображение'),
        ),
    ]
