# Generated by Django 3.0.5 on 2020-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200506_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='steganographic',
            name='key',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ключ для формирования фрактала'),
        ),
    ]
