# Generated by Django 3.0.5 on 2020-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_steganographic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='steganographic',
            name='fr_with_wtmrk_time',
            field=models.FloatField(null=True, verbose_name='Duration generate fractal with watermark'),
        ),
        migrations.AddField(
            model_name='steganographic',
            name='fractal_time',
            field=models.FloatField(null=True, verbose_name='Duration generate fractal'),
        ),
        migrations.AddField(
            model_name='steganographic',
            name='stego_time',
            field=models.FloatField(null=True, verbose_name='Duration generate stego-image'),
        ),
        migrations.AddField(
            model_name='steganographic',
            name='watermark_time',
            field=models.FloatField(null=True, verbose_name='Duration generate watermark'),
        ),
    ]
